language: java
jdk: oraclejdk8
services:
- mysql
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
  - secure: tZYFMuL+arHzviXK7bxhZ251C/FhugritPHTHqIbTJXKjJSSr0d5hEnGGBu5dwfjQPSRJs9gSfSrbVeaAphZwpgCfuxCotlZIyMktgUqFCa6I4sa3vzsR9F6yG1PsJ0v5PQ/6QBKWeXuW/HDjaYuZi4lg09xb1DASkOSCwLwbCImrd3S4Uoc0FG+dk07JCbXcs3BsNhG0ufa4u6Xs3cj4aVQqH+xNLZVVYryBugBlw3zcdfIxkQsBZpE8a05pKi3tFhkY28sJeR7qu6IG845Q9kIZ8Aja0yQSl8+PlYnFdWoyb+r7Jgg0lC8OW2qShSZVToNQq/748BdsNn1BhUjmZtk+fG7nxohesFHpZElOlhsMCED+jE1QeAhG9nF5na475lWWka7gcZVz4CVSBiBUeP8CSP/tcq0iGz2gbZD8Qsg5tTVUHzQ+tks5GV9QF67UIuS3wLj5EAxgJlPXeodYAnw813V5iX588BjcmHyyEUIf020msjcP2Q5NvSOZbJtuLR8y92C2Z6tDYvaL4AnDdIzaAYuXBbCuBs00lrO27d4CAa4WzH9/+TbD9ddUplRJMctSzC0fQ918KR8VCBYZ3IXzn8/EDh6JfDXzG+6UOaNbxuYWghfEVn8PUzBsOF6IAIRXpxIMd5fF/R27cbdoTIhFZBgeXCc/nFRpaV4uks=
  - secure: Dx2RtKgCZGTxNrt56BGnL4Ys9H+uPWaYWaqQhuIqnagN/vgC7NeEzXfnUhjCaSpGEM9irZtpGHknqR3kn8arnDRocG8NlJT4qHeSpX360Rk3pYXbgbmUzT4TG5+ffju3MXLnfHZ31gfFZmd1Km64s3HNuxqyFTPkNipQ4Y1tf/PeMRM6LuGIihjPMlBt6KsaQh9OmbuHw9mvVASsNj8+D4uszj7Ishb0zsZrFQUwgiy8klqrAPFet+KIiAcB6eaMnXRofgSfAAyccyrqRrtGxy21jJKMw6hCv7mChREBWOsoTj4CrUPlnP+phn3YtIkCEeMlcilw1IsFBHXvxG/7kHUjDSnISzYVPVx7L0nTRAE5XjOor4MmJipOCEAb7HJDbV7IobJQyh//EYQ9rxbxFSGDBBxu6p4kWh1MjDVeht3A59jwCPYnSyclaUTSQ/ddGCRkImxZanXyc1v6gJCHE30YuzTlUC5rygPlglgkIBupbgEZc8ZAabLZnLvrz+jdxCylCYnxAmGSg1I4yFUUBIHbl1eer/xEibuiM6LSqwcCYeX/jLHym9R+dBg0p3Fnn8TEEYPxyeq/Lhu0EKLdL+fZswOJU83Tfo2wmki9HMnh52xR5upTvfANBCW8RqVxw90a6tn3Veid3/oAJmB1MIgSmDzX4YPJo9yPt84QqCs=
  - secure: gxOXLI54pQfghS8dMWKVd3mE5hJV/uzLqoVmSyU/9FmB4D5wB9s5Bih4ql4auMyPmzB19Xhgkqfu5fxZ7O5rHaSgpJhtyjsgdc0n2CLff6gO0BwJFasN2JJ1c8rakBRYS3vfST9nZ8SUapfyV+f6yyEBDX1Z7pDg1d6cw4PpYRN0FBvpa7cRi+vANGa9BY8NdEenRAyMEcRLr6hvRu1Axy6fhFaHV5qSWoHPWlPFY5M5KIVj/AfI9r7ys56WVJx1aBRBQVB7mwcmfz+NR5LCQIcibmRNYP6KTohQszokPJmLjr1fLLfctAKs2HOhO8Et7+H2MjxmHtqAmM9fRnyi91fLa/KoUPFSMTBeY8lp7J9jR/ud1rqjTCvrUM4HI96+vuoFXYi72Oac2gfo/w5/GHnwDahRkfuoS3rIzjaYwhoJtg4fNzRLxCK4EWVhQCXMEpiHc+84tPyCOwWvyt1tLu3Jy2rCy0Czm9e5G0yqkZqgukXQd6IZ0962tO1KBOU3I5CiOX7BeqmnsOFpBgjFKHHycJog7I3rXxEVrlKvUpJEcrmDH2ojjH1Cke2kCWm6TUkbKPkaUuxn29s+6x30yOEsbk9ZIVn6pYG+OqpGXPk3l6rC6NJ0r/cyfLDzK/DgAhgyBm6ZedBUqj4ClgCH4Y/iAFsesvguV9ibpY7gZHY=

before_install: "mvn install -DskipTests=true -DfinalName=Tacusci-$TRAVIS_TAG"
deploy:
  file: target/Tacusci-$TRAVIS_TAG.jar
after_success: "curl --ftp-create-dirs -T target/Tacusci-$TRAVIS_TAG.jar -u $FTP_USER:$FTP_PASSWORD web568.webfaction.com/webapps/tacusci_live/deployment/Tacusci-$TRAVIS_TAG.jar"
