language: java
jdk: oraclejdk8
services:
- mysql
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
  - secure: rg1w07SwhMCaRncYOsIXOvAlFYdUnhZ/Qlo2m61h/AIw/yY6g+Dnfn6+5iYARd8n7Dr5O32Uo6I2mgFVVHjwcH1+2nYwIHoD2c3El71hzrKYRf/JWHUe3+XzcGlUBFYYS5hon3JyxSMqbTHEue3eryZiDXJFXtCTbVmS7Wf/mC481VvchsQyLxsTnj9md85ZKjRk4bEdoNvcT/HB8UfVB1/WFpej5zjCzxw0Se0tGUFi3Weah4ta0GGbfxWof2fPbAt+fOgJi9ATYEL7hq+7/tQnrSeQasGnpYxiTzSRmVGraRy7pV4bXi7kuhJrbZO/xo/cWuKIjKsBtj2zrIFX1MLUoTW38jMT8ZnBJC8s2Crlg4YCK5Vd/u64COdGhcGdKuj/ZB0Voj87IpY3DG4Sc4OBAxwCwHwD71THE8A0qmBIRxuH4NveryXsYhM2Y7J/vXA9uCp7wPH1vmeG5XMojiPkJ/AaBKaPJkznrBp/lTk73PlUHjlQOj6mvXwSCL4nRoIqj3Q4TnzTmCBFENf+k0BW5JpKoUrYt5Xhl9gNOSkxqrBTVBxux4cvulk0pVfg1jkZlsXRw5pXaI/puKkyHarmNPM3X3rfWMP1g5GObrTr7Z/J06oCqVSTzIiQ+duSU+6SDnLOMAYBcod/WiDxF2tjY1hgOj7Vzz7tp9neGn8=
  - secure: qeTPiw0Fyp41hAzrZsZtC2/RHmIpbp+siD0Kk+qNvD8mp0t/4qZqporsd+KWuRI+U0eAP1mHjN1xWtg70MUILHqbE4Y5EDywYn5wc68601sbnUVXU0IaqX+pZEk+XM+bZ2XOJG/5BEU6X9KYWU10LkAPopJyybp+Wy4UWfIFew+JZigLoxRm+FSPX8gEZvP4z7HdZwehGpgKNmnBE8cL4xhj/ianA/4CflFDRWXjk6NARgetMYs7wnysOiJsOfCBnOv9TmOdjuDiw2get2grbqCXCAhclrRKUeZIzeOWXu5J1pS2h8iXryhGr0bMyCYcuu6cBScuWJU0Zknx42GdMC6rFPExS23mjNy9447i7PDtU1Iie397VO5yFEMmzg8qm+N9XGPM0u0ie6fQ/bVX/NdtoDtK7tijiFULj+w4yIVWWRl0dH/BHG5vHpZjzDgWjAjIECXPVODR1EDEEDFVqbj7toOjHKdDKgrxSnMRsx8FongnBtYgjqNAIgVJ83KE9SIr8dil0TJiKIaOyMQCXVkcgQUnED1yqapbFZtTwJMWb9rfnuJwg0q+4oBJblDs2k6FT6iykseoH615HjGo+QpuTjROgDxarvZbleI9WFUbjyxsM1LH3V1ErCAoa1cRHnT30DhC76oOWQ3MdMewol3uSF2Vfq4HoYrbtclmEHw=
  - secure: OWCzXJ4mhRgAT+oj2G8Zg2FtCPwqCs5unJEH7kwJndvYjqKqsWAGPjaUUFnyQoAh6zwTTeHxf+37HY9mE7h2UK+/Wh5RjNC4Yo0YdCA+OkhlP8A+heGJ/2BOF9QuFGm7FhUq/gbnMzndP1aHBVOj2KYIz5D+7cKLOIx1/wYhgutBgRLNB95RwwgApWrYXUC63oGyDFA23i+JO3Nzlq2C5Sy1R06dYe8SoWF+hIauJyGIO0txMT9p9+4k6ipi3t0edR97qZPG6C24GRcqxmkGdAzeGASI/GRU3yd/JE+D4KPUkyp3qr6QURbqajKXIPpo+h618fSvydQHJrYzkzAhsMzsvatkiXrQhh24mLutdBXHLdvgRXPH6bVn1VKr20LLV1c0WY0qj4SInqh7yELcWrNYb8gkCE2REutQpa6s5bYO3hb0DH7k5nbynrdNaoJSavTIf3QVBZ7UlJEH1B1+XByZ7GQBgkQVXwxC6VMYkIiB86wgcZnm8/FYTfekRjHtZ6ti7ULkqQns8a/IOTLXi2ZtrQvPIjauGhoIT0cJiCueRs6CzInvjlnfQU7m4UZ8cg2yeQ3mPzCB/1iRQBcjgvnIQ2y/I+XP2QFbQ9xzlJ0Tdqg/beuSKe4JE+r3N0UU+fhor1hiGyBibVCv6jC+naobmLY8YIz4pQ92DHNvOE0=
  matrix:
  - BUILD_VERSION=1.0
after_success: curl --ftp-create-dirs -T target/Tacusci-$TRAVIS_BUILD_NUMBER.jar -u
  $FTP_USER:$FTP_PASSWORD $FTP_ADDRESS
